repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        args:
          - --fix
          - --unsafe-fixes
          - --line-length=88
          - --select=F401,F841,I
          - --per-file-ignores=__init__.py:F401
      - id: ruff-format
        args:
          - --line-length=88
