[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        - **({{commit.scope}})**{% if commit.breaking %} [**breaking**]{% endif %} \
            {{ commit.message }} by {% if commit.author.github_user %}[@{{ commit.author.github_user.login }}](https://github.com/{{ commit.author.github_user.login }}){% else %}{{ commit.author.name }}{% endif %} in [{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }})
    {%- endfor -%}
    {% raw %}\n{% endraw %}\
    {%- for commit in commits %}
        {%- if commit.scope -%}
        {% else -%}
            - {% if commit.breaking %} [**breaking**]{% endif %}\
                {{ commit.message }} by {% if commit.author.github_user %}[@{{ commit.author.github_user.login }}](https://github.com/{{ commit.author.github_user.login }}){% else %}{{ commit.author.name }}{% endif %} in [{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }})
        {% endif -%}
    {% endfor -%}
{% endfor %}
{% if github.contributors | length > 0 %}
### 🎉 Contributors
{% for contributor in github.contributors %}
  - [@{{ contributor.username }}](https://github.com/{{ contributor.username }})
{%- endfor -%}
{% endif %}
{% if version %}
    {% if previous.version %}\
        **Full Changelog**:  [{{ version | trim_start_matches(pat="v") }}]($REPO/compare/{{ previous.version }}..{{ version }})
    {% else %}\
        **Full Changelog**:  [{{ version | trim_start_matches(pat="v") }}]
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}
"""
footer = """
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
postprocessors = [
# Replace the placeholder $REPO with a URL.
    { pattern = '\$REPO', replace = "https://github.com/RapidAI/RapidOCR" }, # replace repository URL
# 去掉每行末尾的无效空格
    { pattern = "(?m)[ \t]+$", replace = "" },
# 将连续多个空行压缩为最多一个空行
    { pattern = "\n{3,}", replace = "\n\n" },
]

[github]
# 填入你的github token，用于拉取commit对应的github用户信息
# token 权限：public_repo 即可
token = ""

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
# Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
#{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/orhun/git-cliff/issues/${2}))"},
]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->🚀 Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },
  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
  { message = "^style", group = "<!-- 5 -->🎨 Styling" },
  { message = "^test", group = "<!-- 6 -->🧪 Testing" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },
  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
  { message = ".*", group = "<!-- 10 -->💼 Other" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "newest"
