if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED NAME)
  message(FATAL_ERROR "INPUT, OUTPUT and NAME are required")
endif()
file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_length)
math(EXPR byte_count "${hex_length} / 2")
string(REGEX REPLACE "(..)" "0x\\1," byte_literals "${hex}")
# CMake's regex replacement can generate the complete initializer body in
# one native operation.  The old nested byte-at-a-time loop took minutes for
# the 300+ KiB Vulkan module, leaving a half-published shader header after
# an interrupted rebuild and making the runtime appear to have no Vulkan
# compute device.
string(REGEX REPLACE "((0x[0-9A-Fa-f][0-9A-Fa-f],){16})" "\\1\n" byte_lines "${byte_literals}")
# `OUTPUT` is supplied without quotes by CMake and may contain another
# command's companion output.  Derive a per-output temporary from its basename
# instead of the former global `.tmp`: two shader headers are generated by a
# single custom command and must never stage through the same filename.
set(output_tmp "${OUTPUT}.embed_tmp")
file(REMOVE "${output_tmp}")
file(WRITE "${output_tmp}" "#pragma once\n#include <array>\n#include <cstdint>\nnamespace ppocr::detail {\nalignas(4) inline constexpr std::array<std::uint8_t, ${byte_count}> ${NAME} = {\n")
file(APPEND "${output_tmp}" "${byte_lines}\n")
file(APPEND "${output_tmp}" "\n};\n}  // namespace ppocr::detail\n")
# CMake's file(RENAME) does not replace an existing destination on every
# Windows/CMake combination.  The old header could therefore be removed while
# a concurrent compile sees a half-generated body.  Move the previous file
# aside first, then publish the complete temporary file atomically by name.
set(previous "${OUTPUT}.previous")
file(REMOVE "${previous}")
if(EXISTS "${OUTPUT}")
  file(RENAME "${OUTPUT}" "${previous}")
endif()
# CMake evaluates every command in one custom-command rule before publishing
# its declared outputs.  The previous two-shader rule published the first
# header only after the second embed script had already staged its own header,
# but both scripts shared this generic temporary name.  Give every output a
# distinct sibling temporary so concurrent/multi-output generation cannot
# truncate the already-built main SPIR-V header.
file(RENAME "${output_tmp}" "${OUTPUT}")
file(REMOVE "${previous}")
